export const dashboardData = [
  {
    number: 1200,
    name: 'Total Orders Delivered',
  },
  {
    number: 45,
    name: 'AVG Promised SLA',
  },
  {
    number: 38,
    name: 'Avg Actual SLA (mins)',
  },
  {
    number: 5,
    name: 'Avg Breach Time',
  },
  {
    number: 1100,
    name: 'Orders Within SLA',
  },
  {
    number: 100,
    name: 'Orders Breaching SLA',
  },
  {
    number: 91.7,
    name: '% Orders within SLA',
  },
   
  {
    number: 15,
    name: 'Avg Handoff time(mins)',
  },
];


  export const dashboardTableData = [
    {
      date: '2025-09-01',
      totalOrders: 120,
      avgPromisedSLA: '30 mins',
      avgActualSLA: '28 mins',
      avgBreachTime: '2 mins',
      ordersWithinSLA: 110,
      ordersBreachingSLA: 10,
      percentWithinSLA: '91.7%',
      clubbedOrders: 20,
      avgHandoffTime: '15 mins',
    },
    {
      date: '2025-09-02',
      totalOrders: 140,
      avgPromisedSLA: '32 mins',
      avgActualSLA: '30 mins',
      avgBreachTime: '2 mins',
      ordersWithinSLA: 130,
      ordersBreachingSLA: 10,
      percentWithinSLA: '92.8%',
      clubbedOrders: 25,
      avgHandoffTime: '14 mins',
    },
    {
      date: '2025-09-03',
      totalOrders: 100,
      avgPromisedSLA: '28 mins',
      avgActualSLA: '27 mins',
      avgBreachTime: '1 min',
      ordersWithinSLA: 95,
      ordersBreachingSLA: 5,
      percentWithinSLA: '95%',
      clubbedOrders: 15,
      avgHandoffTime: '13 mins',
    },
    {
      date: '2025-09-04',
      totalOrders: 160,
      avgPromisedSLA: '35 mins',
      avgActualSLA: '33 mins',
      avgBreachTime: '2 mins',
      ordersWithinSLA: 150,
      ordersBreachingSLA: 10,
      percentWithinSLA: '93.7%',
      clubbedOrders: 30,
      avgHandoffTime: '16 mins',
    },
    {
      date: '2025-09-05',
      totalOrders: 180,
      avgPromisedSLA: '36 mins',
      avgActualSLA: '34 mins',
      avgBreachTime: '2 mins',
      ordersWithinSLA: 170,
      ordersBreachingSLA: 10,
      percentWithinSLA: '94.4%',
      clubbedOrders: 35,
      avgHandoffTime: '15 mins',
    },
    {
      date: '2025-09-06',
      totalOrders: 200,
      avgPromisedSLA: '38 mins',
      avgActualSLA: '36 mins',
      avgBreachTime: '2 mins',
      ordersWithinSLA: 190,
      ordersBreachingSLA: 10,
      percentWithinSLA: '95%',
      clubbedOrders: 40,
      avgHandoffTime: '17 mins',
    },
    {
      date: '2025-09-07',
      totalOrders: 150,
      avgPromisedSLA: '33 mins',
      avgActualSLA: '32 mins',
      avgBreachTime: '1 min',
      ordersWithinSLA: 145,
      ordersBreachingSLA: 5,
      percentWithinSLA: '96.7%',
      clubbedOrders: 28,
      avgHandoffTime: '14 mins',
    },
    {
      date: '2025-09-08',
      totalOrders: 170,
      avgPromisedSLA: '34 mins',
      avgActualSLA: '33 mins',
      avgBreachTime: '1 min',
      ordersWithinSLA: 165,
      ordersBreachingSLA: 5,
      percentWithinSLA: '97.1%',
      clubbedOrders: 32,
      avgHandoffTime: '15 mins',
    },
    {
      date: '2025-09-09',
      totalOrders: 130,
      avgPromisedSLA: '31 mins',
      avgActualSLA: '30 mins',
      avgBreachTime: '1 min',
      ordersWithinSLA: 125,
      ordersBreachingSLA: 5,
      percentWithinSLA: '96.2%',
      clubbedOrders: 22,
      avgHandoffTime: '13 mins',
    },
    {
      date: '2025-09-10',
      totalOrders: 160,
      avgPromisedSLA: '35 mins',
      avgActualSLA: '34 mins',
      avgBreachTime: '1 min',
      ordersWithinSLA: 155,
      ordersBreachingSLA: 5,
      percentWithinSLA: '96.9%',
      clubbedOrders: 30,
      avgHandoffTime: '14 mins',
    },
  ];
